# Generated by Django 3.2.7 on 2021-09-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_question_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='FileStatus',
        ),
    ]
