# Generated by Django 3.2.7 on 2021-09-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_question_filestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestatus',
            name='email',
            field=models.EmailField(default='no', max_length=200),
            preserve_default=False,
        ),
    ]
